<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>TritonRocket 8inch Fall 2016</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>13</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>2025.3017204937648</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>6917.389132549655</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Nose cone [need shoulder]</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>6917.389132549655</CalcMass>
                    <CalcCG>634.9453662336608</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1016.0</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>6</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>6.35</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>304.255546068967</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>SS Nose Tip</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>76.19999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>408.233133</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Nose cone Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1459.2387188337348</CalcMass>
                            <CalcCG>9.524999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>19.049999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>190.0591836332155</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                    <BaseDia>203.2</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>17183.89334508</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>20757.913425563176</CalcMass>
                    <CalcCG>1295.4</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>2590.8</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>203.2</OD>
                    <ID>193.67999999999998</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>193.67999999999998</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>6803.88555</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Trapezoidal fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>50.8</Xb>
                            <CalcMass>7221.910824173959</CalcMass>
                            <CalcCG>475.62745098039215</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>762.0</RootChord>
                            <TipChord>101.6</TipChord>
                            <SemiSpan>279.4</SemiSpan>
                            <SweepDistance>584.1999999999999</SweepDistance>
                            <Thickness>6.35</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>0.0</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Fin Can Tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>4221.81704356197</CalcMass>
                            <CalcCG>379.79999999999995</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>759.5999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>209.54999999999998</OD>
                            <ID>203.2</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>203.2</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Parachute>
                            <KnownMass>680.3885550000001</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Parachute [UPDATE]</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>12.7</Xb>
                            <CalcMass>3059.2865789579114</CalcMass>
                            <CalcCG>38.099999999999994</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>76.19999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <Dia>7620.0</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>355.59999999999997</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0018</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (round 2 mm, 1/16 in)</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>1224.699399</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Recovery Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>99.06</Xb>
                            <CalcMass>4040.9819510076577</CalcMass>
                            <CalcCG>25.4</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>193.67999999999998</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>453.59237</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Avionics Payload</Name>
                            <KnownCG>-177.79999999999998</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-177.79999999999998</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.39999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>453.59237</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Starter Motor [TODO]</Name>
                            <KnownCG>149.85999999999999</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>149.85999999999999</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.39999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>0.7200000000000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord [UPDATE]</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>101.6</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>36.287389600000004</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Pressure Transducer</Name>
                            <KnownCG>228.6</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>228.6</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>45.72</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>76.19999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>127.00586360000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>CO2 Canister</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>101.6</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>